AAA

diff --git a/.github/workflows/ios-ci.yml b/.github/workflows/ios-ci.yml
--- a/.github/workflows/ios-ci.yml
+++ b/.github/workflows/ios-ci.yml
@@ -69,6 +69,18 @@ jobs:
 
       - name: Check disk space after cleaning Bazel cache
         run: df -h
+        
+      - name: Generate Xcode Project
+        run: |
+          set -e
+          # Generate Xcode project using Bazel
+          bazel run //platform/ios:xcodeproj --@rules_xcodeproj//xcodeproj:extra_common_flags="--//:renderer=metal"
+
+          # Check if RenderTest.xcscheme exists
+          if [ -f "MapHero.xcodeproj/xcshareddata/xcschemes/RenderTest.xcscheme" ]; then
+              echo "Error: RenderTest.xcscheme should be removed."
+              exit 1
+          fi
 
       - name: Build Example (Swift) App
         run: bazel build //platform/ios/app-swift:MapHeroApp --//:renderer=metal
